"""Add soft delete support

Revision ID: 2797dcc56267
Revises: fa56cf543ee7
Create Date: 2026-01-19 17:52:17.014090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2797dcc56267'
down_revision: Union[str, None] = 'fa56cf543ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('schools', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'deleted_at')
    op.drop_column('schools', 'deleted_at')
    op.drop_column('payments', 'deleted_at')
    op.drop_column('invoices', 'deleted_at')
    op.drop_column('invoice_items', 'deleted_at')
    # ### end Alembic commands ###
