"""Make student email and enrollment_date required

Revision ID: 2aa5c1fc7f9e
Revises: a2db66ae9368
Create Date: 2026-01-19 18:23:52.680162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa5c1fc7f9e'
down_revision: Union[str, None] = 'a2db66ae9368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'enrollment_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'enrollment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
