"""Remove address fields

Revision ID: a2db66ae9368
Revises: 2797dcc56267
Create Date: 2026-01-19 18:02:36.012254

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2db66ae9368"
down_revision: Union[str, None] = "2797dcc56267"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schools", "contact_email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "schools", "contact_phone", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.drop_column("schools", "address")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools", sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "schools", "contact_phone", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "schools", "contact_email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
